In [3]:
!pip install imutils

  Created wheel for imutils: filename=imutils-0.5.4-py3-none-any.whl size=25862 sha256=4df05009385f6b58dc9eec4b4514713f4109ca05f581439f57b7d4032f2c29d0
  Stored in directory: c:\users\yogeshwaran\appdata\local\pip\cache\wheels\86\d7\0a\4923351ed1cec5d5e24c1eaf8905567b02a0343b24aa873df2
Successfully built imutils


In [7]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install pickle-mixin

  Created wheel for pickle-mixin: filename=pickle_mixin-1.0.2-py3-none-any.whl size=6002 sha256=96ef57064bc440dee6d48fec8b329f13b1bb79fb1c516cbd5cfa44b44c10c0ca
  Stored in directory: c:\users\yogeshwaran\appdata\local\pip\cache\wheels\d0\70\0b\673e09a7ed429660d22352a1b117b4f616a8fc054bdd7eb157
Successfully built pickle-mixin
Note: you may need to restart the kernel to use updated packages.


In [1]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix
from skimage import feature
from imutils import build_montages
from imutils import paths
import numpy as np
import cv2
import os
import pickle

In [2]:
trainingPath=r"D:\STUDIES\Project\Nalaya Thiran Dataset\dataset-20220920T082711Z-001\dataset\spiral\training"
testingPath=r"D:\STUDIES\Project\Nalaya Thiran Dataset\dataset-20220920T082711Z-001\dataset\spiral\testing"

In [3]:
def load_split ( path ) :
    #grab the list of images in the input directory , then initialize
    # the list of data ( i.e. , images ) and class labels
    imagePaths = list ( paths.list_images ( path ) )
    data = [ ]
    labels = [ ]
   #loop over the image paths
    for imagePath in imagePaths :
        #extract the class label from the filename
        label = imagePath.split ( os.path.sep ) [ -2 ]
        print(label)
        #load the input image , convert it to grayscale , and resize
        # it to 200x200 pixels , ignoring aspect ratio
        image = cv2.imread ( imagePath )
        image = cv2.cvtColor ( image , cv2.COLOR_BGR2GRAY )
        image = cv2.resize ( image , ( 200 , 200 ) )
        # threshold the image such that the drawing appears as white
        # on a black background
        image = cv2.threshold(image , 0 , 255 , cv2.THRESH_BINARY_INV | cv2 . THRESH_OTSU)[ 1 ]
        # quantify the image
        features = quantify_image(image)
        print(features)
        # update the data and labels lists , respectively
        data.append ( features )
        labels.append ( label )
    # return the data and labels
    return ( np.array ( data ) , np.array ( labels ) )

In [4]:
def quantify_image(image):
    # compute the histogram 
    features = feature.hog(image, orientations=9,
    pixels_per_cell=(10, 10), cells_per_block=(2, 2),
    transform_sqrt=True, block_norm="L1")
    # return the feature vector
    return features

In [5]:
(X_train, y_train)=load_split(trainingPath)
(X_test,y_test)=load_split(testingPath)

healthy
[0. 0. 0. ... 0. 0. 0.]
healthy
[0. 0. 0. ... 0. 0. 0.]
healthy
[0. 0. 0. ... 0. 0. 0.]
healthy
[0. 0. 0. ... 0. 0. 0.]
healthy
[0. 0. 0. ... 0. 0. 0.]
healthy
[0. 0. 0. ... 0. 0. 0.]
healthy
[0. 0. 0. ... 0. 0. 0.]
healthy
[0. 0. 0. ... 0. 0. 0.]
healthy
[0. 0. 0. ... 0. 0. 0.]
healthy
[0. 0. 0. ... 0. 0. 0.]
healthy
[0. 0. 0. ... 0. 0. 0.]
healthy
[0. 0. 0. ... 0. 0. 0.]
healthy
[0. 0. 0. ... 0. 0. 0.]
healthy
[0. 0. 0. ... 0. 0. 0.]
healthy
[0. 0. 0. ... 0. 0. 0.]
healthy
[0. 0. 0. ... 0. 0. 0.]
healthy
[0. 0. 0. ... 0. 0. 0.]
healthy
[0. 0. 0. ... 0. 0. 0.]
healthy
[0. 0. 0. ... 0. 0. 0.]
healthy
[0. 0. 0. ... 0. 0. 0.]
healthy
[0. 0. 0. ... 0. 0. 0.]
healthy
[0. 0. 0. ... 0. 0. 0.]
healthy
[0. 0. 0. ... 0. 0. 0.]
healthy
[0. 0. 0. ... 0. 0. 0.]
healthy
[0. 0. 0. ... 0. 0. 0.]
healthy
[0. 0. 0. ... 0. 0. 0.]
healthy
[0. 0. 0. ... 0. 0. 0.]
healthy
[0. 0. 0. ... 0. 0. 0.]
healthy
[0. 0. 0. ... 0. 0. 0.]
healthy
[0. 0. 0. ... 0. 0. 0.]
healthy
[0. 0. 0. ... 0. 0. 0.]
healthy


In [6]:
# encode the labels as integers
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)
print(X_train.shape,y_train.shape)

(72, 12996) (72,)


In [24]:
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [7]:
#RANDOM FOREST
print( " [ INFO ] training model Random Forest " )
model = RandomForestClassifier(n_estimators = 100 )
model.fit(X_train , y_train)

 [ INFO ] training model Random Forest 


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [8]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
print( " [ INFO ] training model KNN " )
knn = KNeighborsClassifier(n_neighbors=20)
knn.fit(X_train, y_train)

 [ INFO ] training model KNN 


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=20, p=2,
                     weights='uniform')

In [9]:
#DECISION TREE 
from sklearn.tree import DecisionTreeClassifier
dTree = DecisionTreeClassifier(criterion="gini", random_state=42,max_depth=10, min_samples_leaf=5)   
dTree.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=10, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=5, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=42, splitter='best')

In [10]:
testPaths = list(paths.list_images(testingPath))
idxs = np.arange(0 , len(testPaths))
print(idxs)
idxs = np.random.choice(idxs , size=(25,), replace=False)
print(idxs)
images = []

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[20 24  1 23  5  0 13 18  8 17 16 12  9 28  2 26 21  6  4 22 25 27  7 10
 11]


In [32]:
# RANDOM FOREST
for i in idxs:
    image = cv2.imread(testPaths[i])
    print(image)
    output = image.copy()
    output = cv2.resize(output , (128,128))
    image = cv2.cvtColor(image , cv2.COLOR_BGR2GRAY)
    image = cv2.resize(image , (200,200))
    image = cv2.threshold(image , 0 , 255,cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)[1]
    print(image)
    features = quantify_image(image)
    print(features)
    preds = model.predict([features])
    label = le.inverse_transform(preds)[0]
    print(label)
    color = (0 , 255 , 0) if label == "healthy" else (0 , 0 ,255)
    cv2.putText(output , label , (3, 20) , cv2.FONT_HERSHEY_SIMPLEX , 0.5,color , 2)
    images.append(output)

[[[239 239 239]
  [237 237 237]
  [237 237 237]
  ...
  [232 232 232]
  [232 232 232]
  [242 242 242]]

 [[232 232 232]
  [238 238 238]
  [244 244 244]
  ...
  [235 235 235]
  [239 239 239]
  [243 243 243]]

 [[237 237 237]
  [230 230 230]
  [232 232 232]
  ...
  [231 231 231]
  [234 234 234]
  [243 243 243]]

 ...

 [[240 240 240]
  [238 238 238]
  [239 239 239]
  ...
  [230 230 230]
  [228 228 228]
  [238 238 238]]

 [[239 239 239]
  [233 233 233]
  [235 235 235]
  ...
  [228 228 228]
  [222 222 222]
  [229 229 229]]

 [[242 242 242]
  [233 233 233]
  [234 234 234]
  ...
  [239 239 239]
  [236 236 236]
  [238 238 238]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[0. 0. 0. ... 0. 0. 0.]
parkinson
[[[242 242 242]
  [248 248 248]
  [246 246 246]
  ...
  [228 228 228]
  [239 239 239]
  [238 238 238]]

 [[242 242 242]
  [244 244 244]
  [239 239 239]
  ...
  [237 237 237]
  [239 239 239]
  [228 228 228]]

 [[247 2

healthy
[[[232 232 232]
  [231 231 231]
  [241 241 241]
  ...
  [229 229 229]
  [225 225 225]
  [239 239 239]]

 [[244 244 244]
  [226 226 226]
  [240 240 240]
  ...
  [245 245 245]
  [226 226 226]
  [228 228 228]]

 [[248 248 248]
  [239 239 239]
  [234 234 234]
  ...
  [241 241 241]
  [227 227 227]
  [224 224 224]]

 ...

 [[244 244 244]
  [231 231 231]
  [236 236 236]
  ...
  [230 230 230]
  [235 235 235]
  [235 235 235]]

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ...
  [233 233 233]
  [240 240 240]
  [238 238 238]]

 [[240 240 240]
  [240 240 240]
  [240 240 240]
  ...
  [236 236 236]
  [230 230 230]
  [237 237 237]]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[0. 0. 0. ... 0. 0. 0.]
healthy
[[[232 232 232]
  [239 239 239]
  [242 242 242]
  ...
  [237 237 237]
  [236 236 236]
  [239 239 239]]

 [[236 236 236]
  [231 231 231]
  [233 233 233]
  ...
  [241 241 241]
  [242 242 242]
  [241 241 241]]

 [

In [12]:
#KNN
for i in idxs:
    image = cv2.imread(testPaths[i])
    output = image.copy()
    output = cv2.resize(output , (128,128))
    image = cv2.cvtColor(image , cv2.COLOR_BGR2GRAY)
    image = cv2.resize(image , (200,200))
    image = cv2.threshold(image , 0 , 255,cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)[1]
    features = quantify_image(image)
    preds = knn.predict([features])
    label = le.inverse_transform(preds)[0]
    color = (0 , 255 , 0) if label == "healthy" else (0 , 0 ,255)
    cv2.putText(output , label , (3, 20) , cv2.FONT_HERSHEY_SIMPLEX , 0.5,color , 2)
    images.append(output)

In [13]:
#Decision Tree
for i in idxs:
    image = cv2.imread(testPaths[i])
    output = image.copy()
    output = cv2.resize(output , (128,128))
    image = cv2.cvtColor(image , cv2.COLOR_BGR2GRAY)
    image = cv2.resize(image , (200,200))
    image = cv2.threshold(image , 0 , 255,cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)[1]
    features = quantify_image(image)
    preds = dTree.predict([features])
    label = le.inverse_transform(preds)[0]
    color = (0 , 255 , 0) if label == "healthy" else (0 , 0 ,255)
    cv2.putText(output , label , (3, 20) , cv2.FONT_HERSHEY_SIMPLEX , 0.5,color , 2)
    images.append(output)

In [26]:
montage = build_montages(images , (128,128) ,(3,3))[0]
cv2.imshow("OUTPUT",montage)
cv2.waitKey(0)

-1

In [15]:
# RANDOM FOREST
predictions = model.predict(X_test)
cm = confusion_matrix(y_test , predictions).flatten()
print(cm)
(tn , fp , fn , tp) = cm
accuracy  = (tp + tn) / float(cm.sum())
print(accuracy)

[14  1  3 12]
0.8666666666666667


In [16]:
# KNN
predictions = knn.predict(X_test)
cm = confusion_matrix(y_test , predictions).flatten()
print(cm)
(tn , fp , fn , tp) = cm
accuracy  = (tp + tn) / float(cm.sum())
print(accuracy)

[ 9  6  2 13]
0.7333333333333333


In [17]:
#DECISION TREE 
predictions = dTree.predict(X_test)
cm = confusion_matrix(y_test , predictions).flatten()
print(cm)
(tn , fp , fn , tp) = cm
accuracy  = (tp + tn) / float(cm.sum())
print(accuracy)

[11  4  4 11]
0.7333333333333333


In [18]:
pickle.dump(model , open('parkinsons.pkl','wb'))